#!/usr/bin/php
<?php

use Strukt\Framework\Shell;
use Strukt\Env;
// use Strukt\Framework\Package\Repos;
use Strukt\Framework\Configuration;

use App\Loader as AppLoader;
use App\Kernel as AppKernel;

$loader = require "bootstrap.php";
$loader->add("Schema", __DIR__."/database/schema");

Env::withFile();
Env::set("root_dir", getcwd());
Env::set("json.validation.err", true);

config("app.type","App:Cli");

$kernel = new App\Kernel(new Configuration());
$app = $kernel->getApp();

if(!is_null($app)){

	$app->init();
	$kernel->getRouter()->init();
}

$sh = new Shell();

exit($sh->run($_SERVER["argv"]));




